import type { NextPage } from 'next'
import Head from 'next/head'
import Image from "next/image";
import IndexNavbar from '../components/parts/IndexNavbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
          <title>khisty profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <IndexNavbar/> */}
        
        {/* head cover */}
        <section className="pt-16">
          <div className="container border-1 border-black md:text-center md:mx-auto">
            <div className="flex flex-wrap">
              <div className="w-full px-4 py-6 border-2 border-black">
                <h1 className="font-bold text-2xl">Hello World!👋</h1>
                <h2 className="font-semibold text-base text-slate-500">My Name Khisty N Hanafi.</h2>
                <div className="pt-3">
                  <button className="px-2 py-2 mr-2 text-white bg-black rounded-full hover:bg-gray-600">
                    <svg
                      width="15px"
                      height="15px"
                      className="fill-white"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z" />
                    </svg>
                  </button>
                  <button className="px-2 py-2 mr-2 text-white bg-black rounded-full hover:bg-gray-600">
                    <svg
                      width="15px"
                      height="15px"
                      className="fill-white"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z" />
                    </svg>
                  </button>
                  <button className="px-2 py-2 mr-2 text-white bg-black rounded-full hover:bg-gray-600">
                    <svg
                      width="15px"
                      height="15px"
                      className="fill-white"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path d="M204 6.5C101.4 6.5 0 74.9 0 185.6 0 256 39.6 296 63.6 296c9.9 0 15.6-27.6 15.6-35.4 0-9.3-23.7-29.1-23.7-67.8 0-80.4 61.2-137.4 140.4-137.4 68.1 0 118.5 38.7 118.5 109.8 0 53.1-21.3 152.7-90.3 152.7-24.9 0-46.2-18-46.2-43.8 0-37.8 26.4-74.4 26.4-113.4 0-66.2-93.9-54.2-93.9 25.8 0 16.8 2.1 35.4 9.6 50.7-13.8 59.4-42 147.9-42 209.1 0 18.9 2.7 37.5 4.5 56.4 3.4 3.8 1.7 3.4 6.9 1.5 50.4-69 48.6-82.5 71.4-172.8 12.3 23.4 44.1 36 69.3 36 106.2 0 153.9-103.5 153.9-196.8C384 71.3 298.2 6.5 204 6.5z" />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="w-full self-end">
                <div className="-z-10 absolute bottom-0 -top-12 right-0 bg-slate-300 border-2 border-black md:w-full">
                  <Image
                    className="max-w-full max-auto"
                    src="/images/cover-img.png"
                    width={500}
                    height={850}
                    alt="khistynh-cover"
                  />
                </div>
              </div>
            </div>
          </div>

        </section>
      </main>
    </>
  )
}

export default Home
